# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Pixel Up! 2018"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "The theme for the year"
homepage = "https://pixelup.co.za"
tags = []
features = []
min_version = 0.25

[author]
  name = "Farai Madzima"
  homepage = "https://github.com/mr-farai"
